doctrine:
    dbal:
        # configure these for your database server
        dbname:         '%env(DATABASE_DATABASE)%'
        host:           '%env(DATABASE_HOST)%'
        port:           '%env(DATABASE_PORT)%'
        user:           '%env(DATABASE_USER)%'
        password:       '%env(DATABASE_PASSWORD)%'
        driver:         pdo_pgsql
        server_version: '11.1'
        schema_filter:  ~^(?!(public|topology|tiger))~
        types:
            geometry: CrEOF\Spatial\DBAL\Types\GeometryType
            point: CrEOF\Spatial\DBAL\Types\Geometry\PointType
        mapping_types:
            _text: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            numeric_functions:
                st_distance_sphere: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistanceSphere
        filters:
            refused:
                class: App\Doctrine\RefusedFilter
                enabled: true
