framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: snc_redis.session.handler
        cookie_secure: auto
        cookie_samesite: lax
        name: '_mobilisation_user'
    php_errors:
        log: true
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
