scheb_two_factor:
    google:
        enabled: true
        issuer: Mobilisation
        template: admin/security/two_factor.html.twig

    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
