# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    google:
        enabled: true
        template: security/admin_2fa_form.html.twig

    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
