security:
    hide_user_not_found: false
    erase_credentials: false

    encoders:
        App\Entity\Administrator: bcrypt

    role_hierarchy:
        ROLE_ADMIN_DASHBOARD: ~

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN_DASHBOARD


    access_decision_manager:
        strategy: unanimous

    providers:
        app_administrator_provider:
            entity:
                class: App\Entity\Administrator
                property: emailAddress

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            context: main_context
            anonymous: true
            switch_user: true
            pattern: ^/admin
            provider: app_administrator_provider
            two_factor:
                auth_form_path: admin_security_2fa
                check_path: admin_security_2fa_check
                default_target_path: sonata_admin_dashboard
                always_use_default_target_path: true
            guard:
                authenticators:
                    - App\Security\AdministratorAuthenticator
            logout:
                path: app_admin_logout
                target: /admin/login

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/impersonation/exit, roles: [ROLE_PREVIOUS_ADMIN] }
        - { path: ^/admin, roles: ROLE_ADMIN_DASHBOARD }
