security:
    erase_credentials: false

    access_decision_manager:
        strategy: unanimous

    encoders:
        App\Entity\Actor: bcrypt
        App\Entity\Administrator: bcrypt

    role_hierarchy:
        ROLE_ADMIN_DASHBOARD: ~

        ROLE_ADMIN_ACTORS:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_APP_ADMIN_ACTOR_EXPORT
            - ROLE_APP_ADMIN_ACTOR_LIST
            - ROLE_APP_ADMIN_ACTOR_VIEW
            - ROLE_APP_ADMIN_ACTOR_EDIT

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN_DASHBOARD
            - ROLE_ADMIN_ACTORS

    providers:
        app_actor_provider:
            entity:
                class: App\Entity\Actor
                property: emailAddress
        app_administrator_provider:
            entity:
                class: App\Entity\Administrator
                property: emailAddress

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            context: main_context
            anonymous: true
            provider: app_administrator_provider
            two_factor:
                auth_form_path: admin_security_2fa
                check_path: admin_security_2fa_check
                default_target_path: sonata_admin_dashboard
                always_use_default_target_path: true
            guard:
                authenticators:
                    - App\Security\AdministratorAuthenticator
            logout:
                path: app_admin_logout
                target: app_admin_login

        main:
            context: main_context
            anonymous: true
            provider: app_actor_provider
            switch_user: true
            guard:
                authenticators:
                    - App\Security\ActorAuthenticator
            user_checker: App\Security\ActorChecker
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/profile, roles: [ROLE_USER] }
        - { path: ^/(register|password), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/(login|setup), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/(2fa|logout), role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/admin/impersonation/exit, roles: [ROLE_PREVIOUS_ADMIN] }
        - { path: ^/admin, roles: ROLE_ADMIN_DASHBOARD }
