sonata_admin:
    title: 'Sonata Admin'
    title_logo: bundles/sonataadmin/logo_title.png
    persist_filters: true
    security:
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
        handler: sonata.admin.security.handler.role
    templates:
        layout:  admin/base.html.twig

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
