version: '3.4'

services:
    app:
        image: ${DOCKER_IMAGE}:${DOCKER_APP_TAG}
        env_file:
            - .env.dist
        environment:
            - APP_ENV=test
        build:
            cache_from:
                - ${DOCKER_IMAGE}:${DOCKER_APP_TAG}
                - ${DOCKER_IMAGE}:dev

    db:
        image: ${DOCKER_IMAGE}:${DOCKER_DB_TAG}
        build:
            cache_from:
                - ${DOCKER_IMAGE}:${DOCKER_DB_TAG}
                - ${DOCKER_IMAGE}:dev-db
