<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.queue_consumer' shared service.

$a = ($this->privates['enqueue.client.default.driver'] ?? $this->getEnqueue_Client_Default_DriverService());

return $this->privates['enqueue.client.default.queue_consumer'] = new \Enqueue\Consumption\QueueConsumer(($this->privates['enqueue.client.default.context'] ?? $this->getEnqueue_Client_Default_ContextService()), new \Enqueue\Consumption\ChainExtension(array(0 => new \Enqueue\Client\ConsumptionExtension\SetRouterPropertiesExtension($a), 1 => new \Enqueue\Client\ConsumptionExtension\ExclusiveCommandExtension($a), 2 => ($this->privates['enqueue.consumption.reply_extension'] ?? ($this->privates['enqueue.consumption.reply_extension'] = new \Enqueue\Consumption\Extension\ReplyExtension())), 3 => new \Enqueue\Client\ConsumptionExtension\FlushSpoolProducerExtension(($this->privates['enqueue.client.default.spool_producer'] ?? $this->load('getEnqueue_Client_Default_SpoolProducerService.php'))))), array(), NULL, 10000);
