<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.transport.default.context' shared service.

return $this->privates['enqueue.transport.default.context'] = ($this->privates['enqueue.transport.default.connection_factory'] ?? $this->getEnqueue_Transport_Default_ConnectionFactoryService())->createContext();
