<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.delegate_processor' shared service.

return $this->privates['enqueue.client.default.delegate_processor'] = new \Enqueue\Client\DelegateProcessor(new \Enqueue\Symfony\ContainerProcessorRegistry((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'enqueue.client.default.router_processor' => array('privates', 'enqueue.client.default.router_processor', 'getEnqueue_Client_Default_RouterProcessorService.php', true),
)))->withContext('enqueue.client.default.processor_registry', $this)));
