<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.locator' shared service.

return $this->privates['enqueue.locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'enqueue.client.default.delegate_processor' => array('privates', 'enqueue.client.default.delegate_processor', 'getEnqueue_Client_Default_DelegateProcessorService.php', true),
    'enqueue.client.default.driver' => array('privates', 'enqueue.client.default.driver', 'getEnqueue_Client_Default_DriverService', false),
    'enqueue.client.default.producer' => array('services', 'enqueue.client.default.producer', 'getEnqueue_Client_Default_ProducerService', false),
    'enqueue.client.default.queue_consumer' => array('privates', 'enqueue.client.default.queue_consumer', 'getEnqueue_Client_Default_QueueConsumerService.php', true),
    'enqueue.transport.default.context' => array('privates', 'enqueue.transport.default.context', 'getEnqueue_Transport_Default_ContextService.php', true),
    'enqueue.transport.default.processor_registry' => array('privates', 'enqueue.transport.default.processor_registry', 'getEnqueue_Transport_Default_ProcessorRegistryService.php', true),
    'enqueue.transport.default.queue_consumer' => array('privates', 'enqueue.transport.default.queue_consumer', 'getEnqueue_Transport_Default_QueueConsumerService.php', true),
));
