<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.router_processor' shared service.

return $this->privates['enqueue.client.default.router_processor'] = new \Enqueue\Client\RouterProcessor(($this->privates['enqueue.client.default.driver'] ?? $this->getEnqueue_Client_Default_DriverService()));
