<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.setup_broker_command' shared service.

$this->privates['enqueue.client.setup_broker_command'] = $instance = new \Enqueue\Symfony\Client\SetupBrokerCommand(($this->privates['enqueue.locator'] ?? $this->load('getEnqueue_LocatorService.php')), 'default', 'enqueue.client.%s.driver');

$instance->setName('enqueue:setup-broker');

return $instance;
