<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.menu_provider.lazy' shared service.

return $this->privates['knp_menu.menu_provider.lazy'] = new \Knp\Menu\Provider\LazyProvider(array('sonata_admin_sidebar' => function () {
    return ($this->services['sonata.admin.sidebar_menu'] ?? $this->load('getSonata_Admin_SidebarMenuService.php'));
}));
