<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/login'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/logout'), array(0 => 'IS_AUTHENTICATED_2FA_IN_PROGRESS'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/2fa'), array(0 => 'IS_AUTHENTICATED_2FA_IN_PROGRESS'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin/impersonation/exit'), array(0 => 'ROLE_PREVIOUS_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), array(0 => 'ROLE_ADMIN_DASHBOARD'), NULL);

return $instance;
