<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.twig.status_runtime' shared service.

$this->privates['sonata.core.twig.status_runtime'] = $instance = new \Sonata\CoreBundle\Twig\Extension\StatusRuntime();

$instance->addStatusService(($this->services['sonata.core.flashmessage.manager'] ?? $this->load('getSonata_Core_Flashmessage_ManagerService.php')));

return $instance;
