<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.core.form.type.datetime_range_legacy' shared service.

return $this->services['sonata.core.form.type.datetime_range_legacy'] = new \Sonata\CoreBundle\Form\Type\DateTimeRangeType(($this->services['translator'] ?? $this->getTranslatorService()));
