<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.block.stats' shared service.

return $this->services['sonata.admin.block.stats'] = new \Sonata\AdminBundle\Block\AdminStatsBlockService('sonata.admin.block.stats', ($this->privates['sonata.templating'] ?? $this->load('getSonata_TemplatingService.php')), ($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()));
