<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'scheb_two_factor.security.google_authenticator' shared service.

return $this->services['scheb_two_factor.security.google_authenticator'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Google\GoogleAuthenticator(new \Sonata\GoogleAuthenticator\GoogleAuthenticator(6), NULL, NULL);
