imports:
    - { resource: services_admin.yaml }

parameters:
    locale: '%env(APP_LANGUAGE)%'
    app_language: '%env(APP_LANGUAGE)%'
    app_country: '%env(APP_COUNTRY)%'
    app_timezone: '%env(APP_TIMEZONE)%'
    app_language_ruleset: '%env(APP_LANGUAGE_RULESET)%'
    default_sender: { '%env(DEFAULT_SENDER_EMAIL)%': '%env(DEFAULT_SENDER_NAME)%' }
    pattern_uuid: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appCountry: '%app_country%'
            array $defaultSender: '%default_sender%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    #
    # Doctrine
    #
    App\EventListener\SlugListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
