services:
    _defaults:
        autowire: true
        autoconfigure: true

    admin.administrator:
        class: App\Admin\AdministratorAdmin
        arguments: [~, App\Entity\Administrator, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Administrators' }

    admin.city:
        class: App\Admin\CityAdmin
        arguments: [~, App\Entity\City, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'City' }

    admin.actor:
        class: App\Admin\ActorAdmin
        arguments: [~, App\Entity\Actor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Actors' }

    admin.group:
        class: App\Admin\GroupAdmin
        arguments: [~, App\Entity\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Groups' }

    admin.event:
        class: App\Admin\EventAdmin
        arguments: [~, App\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Events' }

    admin.content:
        class: App\Admin\ContentAdmin
        arguments: [~, App\Entity\Content, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Content' }

    admin.extension.read_only:
        class: App\Admin\Extension\ReadOnlyExtension
        tags:
            - { name: sonata.admin.extension, target: admin.actor }
            - { name: sonata.admin.extension, target: admin.group }
            - { name: sonata.admin.extension, target: admin.event }

    admin.extension.city:
        class: App\Admin\Extension\CityExtension
        tags:
            - { name: sonata.admin.extension, target: admin.actor }
            - { name: sonata.admin.extension, target: admin.group }
            - { name: sonata.admin.extension, target: admin.event }
