parameters:
    locale: 'en'
    app_language: '%env(APP_LANGUAGE)%'
    app_country: '%env(APP_COUNTRY)%'
    app_timezone: '%env(APP_TIMEZONE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appCountry: '%app_country%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    admin.administrator:
        class: App\Admin\AdministratorAdmin
        arguments: [~, App\Entity\Administrator, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'System', label: 'Administrators' }
    admin.actor:
        class: App\Admin\ActorAdmin
        arguments: [~, App\Entity\Actor, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Mobilisation', label: 'Actors' }

    App\EventListener\AdministratorSetupListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
