<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.flush_spool_producer_listener' shared service.

return $this->privates['enqueue.client.default.flush_spool_producer_listener'] = new \Enqueue\Symfony\Client\FlushSpoolProducerListener(($this->privates['enqueue.client.default.spool_producer'] ?? $this->load('getEnqueue_Client_Default_SpoolProducerService.php')));
