<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.client.default.spool_producer' shared service.

return $this->privates['enqueue.client.default.spool_producer'] = new \Enqueue\Client\SpoolProducer(($this->services['enqueue.client.default.producer'] ?? $this->getEnqueue_Client_Default_ProducerService()));
