<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'enqueue.transport.default.queue_consumer' shared service.

return $this->privates['enqueue.transport.default.queue_consumer'] = new \Enqueue\Consumption\QueueConsumer(($this->privates['enqueue.transport.default.context'] ?? $this->load('getEnqueue_Transport_Default_ContextService.php')), new \Enqueue\Consumption\ChainExtension(array(0 => ($this->privates['enqueue.consumption.reply_extension'] ?? ($this->privates['enqueue.consumption.reply_extension'] = new \Enqueue\Consumption\Extension\ReplyExtension())), 1 => new \Enqueue\Consumption\Extension\LogExtension())), array(), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), 10000);
