<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.authenticated_token_handler' shared service.

return $this->privates['scheb_two_factor.authenticated_token_handler'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\AuthenticatedTokenHandler($this->load('getSchebTwoFactor_IpWhitelistHandlerService.php'), $this->parameters['scheb_two_factor.security_tokens']);
