<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Action\SearchAction' shared service.

$this->services['Sonata\AdminBundle\Action\SearchAction'] = $instance = new \Sonata\AdminBundle\Action\SearchAction(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), ($this->services['sonata.admin.search.handler'] ?? $this->load('getSonata_Admin_Search_HandlerService.php')), ($this->services['sonata.admin.global_template_registry'] ?? $this->getSonata_Admin_GlobalTemplateRegistryService()), ($this->services['sonata.admin.breadcrumbs_builder'] ?? $this->load('getSonata_Admin_BreadcrumbsBuilderService.php')));

$instance->setContainer($this);

return $instance;
