<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.flashmessage.twig.runtime' shared service.

return $this->privates['sonata.core.flashmessage.twig.runtime'] = new \Sonata\Twig\Extension\FlashMessageRuntime(($this->services['sonata.core.flashmessage.manager'] ?? $this->load('getSonata_Core_Flashmessage_ManagerService.php')));
