<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.trusted_device_handler' shared service.

return new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\TrustedDeviceHandler($this->load('getSchebTwoFactor_ProviderHandlerService.php'), ($this->privates['scheb_two_factor.null_trusted_device_manager'] ?? ($this->privates['scheb_two_factor.null_trusted_device_manager'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Trusted\NullTrustedDeviceManager())), false);
