<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.ip_whitelist_handler' shared service.

return new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\IpWhitelistHandler($this->load('getSchebTwoFactor_TrustedDeviceHandlerService.php'), new \Scheb\TwoFactorBundle\Security\TwoFactor\IpWhitelist\DefaultIpWhitelistProvider(array()));
