<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'scheb_two_factor.firewall_context' shared service.

return $this->services['scheb_two_factor.firewall_context'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\TwoFactorFirewallContext(array('admin' => new \Scheb\TwoFactorBundle\Security\TwoFactor\TwoFactorFirewallConfig(array('auth_form_path' => 'admin_security_2fa', 'check_path' => 'admin_security_2fa_check', 'default_target_path' => 'sonata_admin_dashboard', 'always_use_default_target_path' => true, 'success_handler' => NULL, 'failure_handler' => NULL, 'authentication_required_handler' => NULL, 'auth_code_parameter_name' => '_auth_code', 'trusted_parameter_name' => '_trusted', 'multi_factor' => false, 'csrf_token_generator' => NULL, 'csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'two_factor', 'provider' => NULL))));
