<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.two_factor.admin' shared service.

return $this->privates['security.authentication.provider.two_factor.admin'] = new \Scheb\TwoFactorBundle\Security\Authentication\Provider\TwoFactorAuthenticationProvider('admin', array('auth_form_path' => 'admin_security_2fa', 'check_path' => 'admin_security_2fa_check', 'default_target_path' => 'sonata_admin_dashboard', 'always_use_default_target_path' => true, 'success_handler' => NULL, 'failure_handler' => NULL, 'authentication_required_handler' => NULL, 'auth_code_parameter_name' => '_auth_code', 'trusted_parameter_name' => '_trusted', 'multi_factor' => false, 'csrf_token_generator' => NULL, 'csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'two_factor', 'provider' => NULL), ($this->privates['scheb_two_factor.provider_registry'] ?? $this->load('getSchebTwoFactor_ProviderRegistryService.php')), new \Scheb\TwoFactorBundle\Security\TwoFactor\Backup\NullBackupCodeManager());
