<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'scheb_two_factor.form_controller' shared service.

return $this->services['scheb_two_factor.form_controller'] = new \Scheb\TwoFactorBundle\Controller\FormController(($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->privates['scheb_two_factor.provider_registry'] ?? $this->load('getSchebTwoFactor_ProviderRegistryService.php')), ($this->services['scheb_two_factor.firewall_context'] ?? $this->load('getSchebTwoFactor_FirewallContextService.php')), false);
